# Generated by Django 5.2 on 2025-04-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=100)),
                ('bedroom_count', models.PositiveIntegerField()),
            ],
        ),
    ]
